### ISSUE TITLE
Error messages in "Explorando data frames"

### ISSUE THREAD

**Issue by Zulemma** [swcarpentry/r-novice-gapminder-es#122]
In "Explorando Data Frames" episode when we run 

`gatos <- rbind(gatos, nueva_fila)`

there is no an error message about "invalid factor level". May add a little a chunk of code and show the error message obtained to become clear.

![errormessage](https://user-images.githubusercontent.com/39578811/130987223-6a0cc926-6388-4a48-8d61-b1a88eabed47.jpg)

**Comment by nselem** [comment]
Dear Zulema
Thank you for pointing this out; the problem is that the color column was not a factor. I have added a chunk to convert it into a factor column, and now the error should be visible. Since these episodes are in r-markdown the output chunks are automatically generated. But now the following error should be shown: 
Warning message:  
In `[<-.factor`(`*tmp*`, ri, value = "carey") :  
  invalid factor level, NA generated
